### PR TITLE
stream: Update doc about sources attribute support

### PR DESCRIPTION
**Pull request by mhdzumair**

### CODE REVIEW

**Comment by jaruba** [comment]
@mhdzumair i feel like it should be mentioned that this property should only be set if `infoHash` is also set for the `stream` object

**Comment by mhdzumair** [comment]
updated

**Comment by jaruba** [comment]
I believe that the wording of "torrent announce URLs" can be considered ambiguous, it should be "torrent tracker URLs" imo

**Comment by jaruba** [comment]
and it should be mentioned that both HTTP and UDP trackers are supported

**Comment by mhdzumair** [comment]
I hope It's now correctly interpreted your suggestion.

**Review by jaruba — APPROVED** [review]

**Comment by jaruba** [comment]
@mhdzumair thanks!

**Pull request merged**
